FIX: More

diff --git a/.github/workflows/cibuildwheel.yml b/.github/workflows/cibuildwheel.yml
--- a/.github/workflows/cibuildwheel.yml
+++ b/.github/workflows/cibuildwheel.yml
@@ -91,12 +91,15 @@ jobs:
       - name: Triage dependencies
         run: |
           if [[ "${{ matrix.python-version }}" != "3.13" ]]; then
-            echo "PIP_EXTRA=wfdb \"numpy<2\" numba pytest-error-for-skips" | tee -a $GITHUB_ENV
+            echo "PIP_EXTRA=wfdb numpy<2 numba pytest-error-for-skips" | tee -a $GITHUB_ENV
             echo "PYTEST_EXTRA=--error-for-skips" | tee -a $GITHUB_ENV
           fi
-      - run: python -m pip install ./dist/*.whl pytest edfio $PIP_EXTRA --only-binary="numpy,numba,edfio"
+      - run: python -m pip install ./dist/*.whl pytest pytest-cov edfio $PIP_EXTRA --only-binary="numpy,numba,edfio"
       - run: pytest -rfEXs --cov-report=xml --tb=short --cov-branch --junit-xml=junit-results.xml --color=yes $PYTEST_EXTRA tests/
-      # TODO: Add codecov?
+      - uses: codecov/codecov-action@v5
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+        if: success() || failure()
 
   build_sdist:
     needs: style
